apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-mario.fullname" . }}-deployment
  labels:
  {{- include "k8s-mario.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mario
    {{- include "k8s-mario.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mario
      {{- include "k8s-mario.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        name: mario-container
        ports:
        - containerPort: 80
        resources: {}
