apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-mario.fullname" . }}-service
  labels:
  {{- include "k8s-mario.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mario
  {{- include "k8s-mario.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}
